name: Generate ICS Calendars

permissions:
  contents: write

on:
  schedule:
    - cron: '0 /1 * * *'
  workflow_dispatch:

jobs:
  generate-ics:
    runs-on: ubuntu-latest
    environment: kcalendar

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Generate Karmine Calendar
        run: node dist/main.js
        env:
          PANDASCORE_TOKEN: ${{ secrets.PANDASCORE_TOKEN }}
          ICAL_PATH: karmine.ics

      - name: Generate Mates Calendar
        run: node dist/main.js
        env:
          PANDASCORE_TOKEN: ${{ secrets.PANDASCORE_TOKEN }}
          TEAM_NAME: Gentle Mates
          ICAL_PATH: mates.ics

      - name: Generate Vitality Calendar
        run: node dist/main.js
        env:
          PANDASCORE_TOKEN: ${{ secrets.PANDASCORE_TOKEN }}
          TEAM_NAME: Vitality
          ICAL_PATH: vitality.ics

      - name: Generate Solary Calendar
        run: node dist/main.js
        env:
          PANDASCORE_TOKEN: ${{ secrets.PANDASCORE_TOKEN }}
          TEAM_NAME: Solary
          ICAL_PATH: solary.ics

      - name: Prepare public folder for GitHub Pages
        run: |
          mkdir -p public/ical
          cp karmine.ics public/ical/karmine.ics
          cp mates.ics public/ical/mates.ics
          cp vitality.ics public/ical/vitality.ics
          cp solary.ics public/ical/solary.ics

      - name: Deploy .ics to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages
