name: Generate ICS Calendars

permissions:
  contents: write

on:
  pull_request:
    branches: [ "main", "dev" ]
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  generate-ics:
    runs-on: ubuntu-latest
    environment: kcalendar

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Generate All Calendars
        run: node dist/main.js
        env:
          PANDASCORE_TOKEN: ${{ secrets.PANDASCORE_TOKEN }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          TEAM_NAME: Karmine, Gentle Mates, Vitality, Solary
          ICAL_PATH: karmine.ics, mates.ics, vitality.ics, solary.ics

      - name: Prepare public folder for GitHub Pages
        run: |
          mkdir -p public/ical
          
          shopt -s nullglob
          ics_files=(*.ics)
          if (( ${#ics_files[@]} )); then
            cp "${ics_files[@]}" public/ical/
          else
            echo "::warning::Prepare public folder for GitHub Pages failed â€” no files generated"
          fi

      - name: Deploy .ics to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages
